DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE "Roles" (
    "RoleID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleName" VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE "Faculty" (
    "FacultyID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FacultyName" VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE "Users" (
    "UserID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Username" VARCHAR(100) NOT NULL UNIQUE,
    "PasswordHash" VARCHAR(200) NOT NULL,
    "PasswordSalt" VARCHAR(200) NOT NULL,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" BYTEA NOT NULL,
    "Email" VARCHAR(200) NOT NULL UNIQUE,
    "RoleID" INTEGER NOT NULL REFERENCES "Roles"("RoleID"),
    "IsBlocked" BOOLEAN NOT NULL DEFAULT FALSE,
    "FacultyID" INTEGER NULL REFERENCES "Faculty"("FacultyID"),
    "PasswordResetToken" VARCHAR(255) NULL,
    "PasswordResetTokenExpiry" TIMESTAMPTZ NULL,
    "IsTwoFactorEnabled" BOOLEAN NOT NULL DEFAULT FALSE,
    "TwoFactorCode" VARCHAR(20) NULL,
    "TwoFactorCodeExpiry" TIMESTAMPTZ NULL
);

CREATE TABLE "Authors" (
    "AuthorID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" VARCHAR(100) NOT NULL
);

CREATE TABLE "Categories" (
    "CategoryID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryName" VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE "Publisher" (
    "PublisherID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PublisherName" VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE "Books" (
    "BookID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(300) NOT NULL,
    "Description" TEXT NULL,
    "PublishYear" INTEGER NULL,
    "CategoryID" INTEGER NOT NULL REFERENCES "Categories"("CategoryID"),
    "AuthorID" INTEGER NOT NULL REFERENCES "Authors"("AuthorID"),
    "PublisherID" INTEGER NULL REFERENCES "Publisher"("PublisherID"),
    "ImagePath" TEXT NULL,
    "FilePath" TEXT NULL,
    "RequiresSubscription" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE "Subscriptions" (
    "SubscriptionID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FacultyID" INTEGER NULL REFERENCES "Faculty"("FacultyID"),
    "Name" VARCHAR(200) NOT NULL,
    "StartDate" TIMESTAMPTZ NULL,
    "EndDate" TIMESTAMPTZ NULL,
    "DurationDays" INTEGER NULL,
    "Status" VARCHAR(50) NULL,
    "RequestedByUserID" INTEGER NULL
);

CREATE TABLE "SubscriptionRequests" (
    "SubscriptionRequestID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FacultyID" INTEGER NOT NULL REFERENCES "Faculty"("FacultyID"),
    "SubscriptionID" INTEGER NOT NULL REFERENCES "Subscriptions"("SubscriptionID"),
    "RequestedByUserID" INTEGER NOT NULL REFERENCES "Users"("UserID"),
    "RequestedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Pending'
);

CREATE TABLE "BookLogs" (
    "LogID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" INTEGER NOT NULL REFERENCES "Users"("UserID"),
    "BookID" INTEGER NOT NULL REFERENCES "Books"("BookID"),
    "ActionType" VARCHAR(20) NOT NULL,
    "ActionAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Reviews" (
    "ReviewID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" INTEGER NOT NULL REFERENCES "Users"("UserID"),
    "BookID" INTEGER NOT NULL REFERENCES "Books"("BookID"),
    "Rating" INTEGER NOT NULL,
    "Comment" TEXT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "AuditLog" (
    "AuditLogID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TableName" VARCHAR(100) NOT NULL,
    "ActionType" VARCHAR(20) NOT NULL,
    "RecordID" INTEGER NULL,
    "UserName" VARCHAR(100) NULL,
    "OldData" TEXT NULL,
    "NewData" TEXT NULL,
    "AuditDate" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "AuditLogBackup" (
    "AuditLogID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TableName" VARCHAR(100) NOT NULL,
    "ActionType" VARCHAR(20) NOT NULL,
    "UserName" VARCHAR(100) NULL,
    "OldData" TEXT NULL,
    "NewData" TEXT NULL,
    "AuditDate" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "AuthorBook" (
    "AuthorBookID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AuthorID" INTEGER NOT NULL REFERENCES "Authors"("AuthorID"),
    "BookID" INTEGER NOT NULL REFERENCES "Books"("BookID")
);

CREATE TABLE "Bookmarks" (
    "BookmarkID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserID" INTEGER NOT NULL REFERENCES "Users"("UserID"),
    "BookID" INTEGER NOT NULL REFERENCES "Books"("BookID"),
    "Page" INTEGER NULL,
    "Position" VARCHAR(100) NULL,
    "Title" VARCHAR(255) NULL,
    "Note" TEXT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX "IX_Users_Username" ON "Users" ("Username");
CREATE INDEX "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX "IX_Users_RoleID" ON "Users" ("RoleID");
CREATE INDEX "IX_Users_FacultyID" ON "Users" ("FacultyID");
CREATE INDEX "IX_Books_Title" ON "Books" ("Title");
CREATE INDEX "IX_Books_CategoryID" ON "Books" ("CategoryID");
CREATE INDEX "IX_Books_PublisherID" ON "Books" ("PublisherID");
CREATE INDEX "IX_BookLogs_UserID" ON "BookLogs" ("UserID");
CREATE INDEX "IX_BookLogs_BookID" ON "BookLogs" ("BookID");
CREATE INDEX "IX_BookLogs_ActionType" ON "BookLogs" ("ActionType");
CREATE INDEX "IX_BookLogs_ActionAt" ON "BookLogs" ("ActionAt");
CREATE INDEX "IX_Reviews_BookID" ON "Reviews" ("BookID");
CREATE INDEX "IX_Reviews_UserID" ON "Reviews" ("UserID");
CREATE INDEX "IX_Subscriptions_FacultyID" ON "Subscriptions" ("FacultyID");
CREATE INDEX "IX_Subscriptions_FacultyID_Status" ON "Subscriptions" ("FacultyID", "Status");
CREATE INDEX "IX_Bookmarks_UserID_BookID" ON "Bookmarks" ("UserID", "BookID");
CREATE INDEX "IX_Bookmarks_UserID" ON "Bookmarks" ("UserID");

INSERT INTO "Roles" ("RoleName")
VALUES ('Admin'), ('Librarian'), ('Student'), ('InstitutionRepresentative'), ('Guest');

INSERT INTO "Faculty" ("FacultyName")
VALUES
    ('Информационные технологии'),
    ('Экономика и управление'),
    ('Гуманитарные науки'),
    ('Технические специальности');

INSERT INTO "Users" ("Username", "PasswordHash", "PasswordSalt", "FirstName", "LastName", "Email", "RoleID")
SELECT
    'admin',
    'LiixdeKKV/NuDCva4WmKdP7hQ1K1x1tXA21tin06S0b9jSOMY3FKkGcJzkYquImth948QBS03I0Qwec72/5p/g==',
    'seed-admin-salt-2026',
    'Admin',
    convert_to('Иванов', 'UTF8'),
    'admin@library.com',
    "RoleID"
FROM "Roles"
WHERE "RoleName" = 'Admin'
LIMIT 1;

INSERT INTO "Authors" ("FirstName", "LastName")
VALUES
    ('Фёдор', 'Достоевский'),
    ('Лев', 'Толстой'),
    ('Михаил', 'Булгаков'),
    ('Александр', 'Пушкин'),
    ('Рэй', 'Брэдбери'),
    ('Роберт', 'Мартин'),
    ('Эндрю', 'Хант'),
    ('Дэвид', 'Томас'),
    ('Мартин', 'Фаулер'),
    ('Герберт', 'Шилдт');

INSERT INTO "Categories" ("CategoryName")
VALUES
    ('Классическая литература'),
    ('Роман'),
    ('Фантастика'),
    ('Философия'),
    ('Программирование');

INSERT INTO "Publisher" ("PublisherName")
VALUES
    ('Эксмо'),
    ('АСТ'),
    ('Азбука'),
    ('МИФ');

INSERT INTO "Books" ("Title", "Description", "PublishYear", "CategoryID", "AuthorID", "PublisherID")
VALUES
(
    'Преступление и наказание',
    'Психологический роман о вине и искуплении',
    1866,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Философия' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Достоевский' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'Эксмо' LIMIT 1)
),
(
    'Война и мир',
    'Роман-эпопея о судьбах людей на фоне войны',
    1869,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Роман' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Толстой' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'АСТ' LIMIT 1)
),
(
    'Мастер и Маргарита',
    'Мистический роман о добре и зле',
    1967,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Классическая литература' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Булгаков' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'Азбука' LIMIT 1)
),
(
    'Евгений Онегин',
    'Роман в стихах',
    1833,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Классическая литература' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Пушкин' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'МИФ' LIMIT 1)
),
(
    '451 градус по Фаренгейту',
    'Антиутопия о запрете книг',
    1953,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Фантастика' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Брэдбери' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'АСТ' LIMIT 1)
);

UPDATE "Books" SET "ImagePath" = 'https://i.postimg.cc/L8n0hYsV/prestup.jpg' WHERE "Title" = 'Преступление и наказание';
UPDATE "Books" SET "ImagePath" = 'https://i.postimg.cc/3xdbW4wp/vim.webp' WHERE "Title" = 'Война и мир';
UPDATE "Books" SET "ImagePath" = 'https://i.postimg.cc/pX062YPk/mim.webp' WHERE "Title" = 'Мастер и Маргарита';
UPDATE "Books" SET "ImagePath" = 'https://i.postimg.cc/qMm5kXpL/evgen.webp' WHERE "Title" = 'Евгений Онегин';
UPDATE "Books" SET "ImagePath" = 'https://i.postimg.cc/65Hm9LBh/451.webp' WHERE "Title" = '451 градус по Фаренгейту';

UPDATE "Books" SET "FilePath" = '/books/Dostoevskyi_Prestuplenie_i_nakazanie.pdf' WHERE "Title" = 'Преступление и наказание';
UPDATE "Books" SET "FilePath" = '/books/Tolstoy_Voina_i_mir.pdf' WHERE "Title" = 'Война и мир';
UPDATE "Books" SET "FilePath" = '/books/Bulgakov_Master_i_Margarita.pdf' WHERE "Title" = 'Мастер и Маргарита';
UPDATE "Books" SET "FilePath" = '/books/Pushkin_Evgenyi_Onegin.pdf' WHERE "Title" = 'Евгений Онегин';
UPDATE "Books" SET "FilePath" = '/books/451_градус_по_Фаренгейту__ata.pdf' WHERE "Title" = '451 градус по Фаренгейту';

INSERT INTO "Books"
("Title", "Description", "PublishYear", "CategoryID", "AuthorID", "PublisherID", "FilePath", "ImagePath", "RequiresSubscription")
VALUES
(
    'Чистый код',
    'Практики написания читаемого и поддерживаемого кода',
    2008,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Программирование' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Мартин' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'МИФ' LIMIT 1),
    '/books/Robert_Sesil_Martin_Chistyiy_kod._Sozdanie_analiz_i_refaktoring.pdf',
    'https://i.postimg.cc/9MCbx7mx/clean-code.jpg',
    FALSE
),
(
    'Программист-прагматик',
    'Классическая книга о мышлении разработчика',
    1999,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Программирование' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Хант' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'АСТ' LIMIT 1),
    '/books/Программист-прагматик, 2-е юбилейное издание.pdf',
    'https://i.postimg.cc/8zwL10Nh/pragmatic.webp',
    FALSE
),
(
    'Refactoring',
    'Улучшение существующего кода без изменения поведения',
    1999,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Программирование' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Фаулер' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'Азбука' LIMIT 1),
    '/books/Fauler_Martin_Refaktoring.pdf',
    'https://i.postimg.cc/261Q97pB/refactoring.webp',
    FALSE
),
(
    'Java. Полное руководство',
    'Подробное руководство по языку Java',
    2018,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Программирование' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Шилдт' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'Эксмо' LIMIT 1),
    '/books/codelibs.ru_java-polnoe-rukovodstvo-12-e-izd.pdf',
    'https://i.postimg.cc/c4n3nJZd/java.jpg',
    FALSE
),
(
    'Эксклюзивный курс по машинному обучению',
    'Углубленный курс по современным технологиям искусственного интеллекта и машинного обучения. Включает практические примеры и кейсы.',
    2024,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Философия' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Достоевский' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'МИФ' LIMIT 1),
    '/books/Mashinnoe-obuchenie-bez-lishnikh-slov.pdf',
    'https://i.postimg.cc/GhGFMCgy/aaaaaaaaaaaaaaaaaaaa.webp',
    TRUE
),
(
    'Премиум коллекция научных статей',
    'Собрание лучших научных статей по программированию, архитектуре ПО и современным технологиям разработки.',
    2024,
    (SELECT "CategoryID" FROM "Categories" WHERE "CategoryName" = 'Классическая литература' LIMIT 1),
    (SELECT "AuthorID" FROM "Authors" WHERE "LastName" = 'Толстой' LIMIT 1),
    (SELECT "PublisherID" FROM "Publisher" WHERE "PublisherName" = 'АСТ' LIMIT 1),
    '/books/sbornik_stud.pdf',
    'https://i.postimg.cc/ZKp8fSs6/aaao.jpg',
    TRUE
);

CREATE OR REPLACE FUNCTION public.audit_generic_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO auditlog (tablename, actiontype, username, newdata)
        VALUES (TG_TABLE_NAME, 'INSERT', current_user, row_to_json(NEW)::text);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO auditlog (tablename, actiontype, username, olddata, newdata)
        VALUES (TG_TABLE_NAME, 'UPDATE', current_user, row_to_json(OLD)::text, row_to_json(NEW)::text);
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO auditlog (tablename, actiontype, username, olddata)
        VALUES (TG_TABLE_NAME, 'DELETE', current_user, row_to_json(OLD)::text);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_users_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    old_payload jsonb;
    new_payload jsonb;
BEGIN
    IF TG_OP = 'INSERT' THEN
        new_payload := jsonb_build_object(
            'UserID', NEW.userid,
            'Username', NEW.username,
            'FirstName', NEW.firstname,
            'Email', NEW.email,
            'RoleID', NEW.roleid,
            'FacultyID', NEW.facultyid,
            'IsBlocked', NEW.isblocked,
            'PasswordResetTokenExpiry', NEW.passwordresettokenexpiry
        );
        INSERT INTO auditlog (tablename, actiontype, username, newdata)
        VALUES ('Users', 'INSERT', current_user, new_payload::text);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        old_payload := jsonb_build_object(
            'UserID', OLD.userid,
            'Username', OLD.username,
            'FirstName', OLD.firstname,
            'Email', OLD.email,
            'RoleID', OLD.roleid,
            'FacultyID', OLD.facultyid,
            'IsBlocked', OLD.isblocked,
            'PasswordResetTokenExpiry', OLD.passwordresettokenexpiry
        );
        new_payload := jsonb_build_object(
            'UserID', NEW.userid,
            'Username', NEW.username,
            'FirstName', NEW.firstname,
            'Email', NEW.email,
            'RoleID', NEW.roleid,
            'FacultyID', NEW.facultyid,
            'IsBlocked', NEW.isblocked,
            'PasswordResetTokenExpiry', NEW.passwordresettokenexpiry
        );
        INSERT INTO auditlog (tablename, actiontype, username, olddata, newdata)
        VALUES ('Users', 'UPDATE', current_user, old_payload::text, new_payload::text);
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        old_payload := jsonb_build_object(
            'UserID', OLD.userid,
            'Username', OLD.username,
            'FirstName', OLD.firstname,
            'Email', OLD.email,
            'RoleID', OLD.roleid,
            'FacultyID', OLD.facultyid,
            'IsBlocked', OLD.isblocked
        );
        INSERT INTO auditlog (tablename, actiontype, username, olddata)
        VALUES ('Users', 'DELETE', current_user, old_payload::text);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_roles_audit
AFTER INSERT OR UPDATE OR DELETE ON "Roles"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_faculty_audit
AFTER INSERT OR UPDATE OR DELETE ON "Faculty"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_authors_audit
AFTER INSERT OR UPDATE OR DELETE ON "Authors"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_categories_audit
AFTER INSERT OR UPDATE OR DELETE ON "Categories"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_publisher_audit
AFTER INSERT OR UPDATE OR DELETE ON "Publisher"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_books_audit
AFTER INSERT OR UPDATE OR DELETE ON "Books"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_subscriptions_audit
AFTER INSERT OR UPDATE OR DELETE ON "Subscriptions"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_subscription_requests_audit
AFTER INSERT OR UPDATE OR DELETE ON "SubscriptionRequests"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_booklogs_audit
AFTER INSERT OR UPDATE OR DELETE ON "BookLogs"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_reviews_audit
AFTER INSERT OR UPDATE OR DELETE ON "Reviews"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_authorbook_audit
AFTER INSERT OR UPDATE OR DELETE ON "AuthorBook"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_bookmarks_audit
AFTER INSERT OR UPDATE OR DELETE ON "Bookmarks"
FOR EACH ROW EXECUTE FUNCTION public.audit_generic_trigger();

CREATE TRIGGER trg_users_audit
AFTER INSERT OR UPDATE OR DELETE ON "Users"
FOR EACH ROW EXECUTE FUNCTION public.audit_users_trigger();

DO $$
DECLARE
    r RECORD;
    c RECORD;
    tbl text;
BEGIN
    FOR r IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_type = 'BASE TABLE'
          AND table_name <> lower(table_name)
        ORDER BY table_name
    LOOP
        EXECUTE format('ALTER TABLE public.%I RENAME TO %I;', r.table_name, lower(r.table_name));
    END LOOP;

    FOR c IN
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND column_name <> lower(column_name)
        ORDER BY table_name, ordinal_position
    LOOP
        tbl := lower(c.table_name);
        EXECUTE format('ALTER TABLE public.%I RENAME COLUMN %I TO %I;', tbl, c.column_name, lower(c.column_name));
    END LOOP;
END $$;

ALTER TABLE users ADD COLUMN IF NOT EXISTS failedloginattemptcount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lockoutendutc TIMESTAMPTZ NULL;

CREATE TABLE IF NOT EXISTS readingprogress (
    readingprogressid SERIAL PRIMARY KEY,
    userid INTEGER NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
    bookid INTEGER NOT NULL REFERENCES books(bookid) ON DELETE CASCADE,
    lastpage INTEGER NULL,
    lastposition TEXT NULL,
    percent INTEGER NULL,
    updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(userid, bookid)
);

CREATE INDEX IF NOT EXISTS ix_readingprogress_userid ON readingprogress(userid);
CREATE INDEX IF NOT EXISTS ix_readingprogress_updatedat ON readingprogress(updatedat DESC);

CREATE TABLE IF NOT EXISTS bookcategories (
    bookid INT NOT NULL REFERENCES books(bookid) ON DELETE CASCADE,
    categoryid INT NOT NULL REFERENCES categories(categoryid) ON DELETE CASCADE,
    PRIMARY KEY (bookid, categoryid)
);

INSERT INTO bookcategories (bookid, categoryid)
SELECT bookid, categoryid FROM books WHERE categoryid IS NOT NULL
ON CONFLICT (bookid, categoryid) DO NOTHING;

ALTER TABLE books DROP COLUMN IF EXISTS categoryid;
CREATE INDEX IF NOT EXISTS IX_bookcategories_categoryid ON bookcategories(categoryid);

CREATE TABLE IF NOT EXISTS bookrequests (
  bookrequestid SERIAL PRIMARY KEY,
  userid INT NOT NULL REFERENCES users(userid) ON DELETE CASCADE,
  bookid INT NOT NULL REFERENCES books(bookid) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'Pending',
  createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  decidedat TIMESTAMPTZ NULL,
  decisionuserid INT NULL REFERENCES users(userid),
  CONSTRAINT uq_bookrequests_userid_bookid UNIQUE (userid, bookid)
);

CREATE INDEX IF NOT EXISTS IX_bookrequests_userid ON bookrequests(userid);
CREATE INDEX IF NOT EXISTS IX_bookrequests_bookid ON bookrequests(bookid);
CREATE INDEX IF NOT EXISTS IX_bookrequests_status ON bookrequests(status);

CREATE TABLE IF NOT EXISTS subscriptioncategories (
  subscriptionid INT NOT NULL REFERENCES subscriptions(subscriptionid) ON DELETE CASCADE,
  categoryid INT NOT NULL REFERENCES categories(categoryid) ON DELETE CASCADE,
  CONSTRAINT PK_subscriptioncategories PRIMARY KEY (subscriptionid, categoryid)
);

CREATE INDEX IF NOT EXISTS IX_subscriptioncategories_categoryid ON subscriptioncategories(categoryid);
CREATE INDEX IF NOT EXISTS IX_subscriptioncategories_subscriptionid ON subscriptioncategories(subscriptionid);
